//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung;User ID=s" +
            "a;Password=123456")]
        public string strConn {
            get {
                return ((string)(this["strConn"]));
            }
            set {
                this["strConn"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung;User ID=s" +
            "a;Password=123456")]
        public string DoAn_QLTiemChungConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChungConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung;User ID=s" +
            "a;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChungConnectionString1 {
            get {
                return ((string)(this["DoAn_QLTiemChungConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung;User ID=s" +
            "a;Password=123456;Encrypt=False;TrustServerCertificate=True")]
        public string DoAn_QLTiemChungConnectionString2 {
            get {
                return ((string)(this["DoAn_QLTiemChungConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung;User ID=s" +
            "a;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChungConnectionString3 {
            get {
                return ((string)(this["DoAn_QLTiemChungConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung2;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung2ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung4;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung4ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung2;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung2ConnectionString1 {
            get {
                return ((string)(this["DoAn_QLTiemChung2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung6;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung6ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung3;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung3ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung7;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung7ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung7ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung8;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung8ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung8ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung4;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung4ConnectionString1 {
            get {
                return ((string)(this["DoAn_QLTiemChung4ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung5;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung5ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OTH2ANP\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung7;User ID=" +
            "sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung7ConnectionString1 {
            get {
                return ((string)(this["DoAn_QLTiemChung7ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChung10;User ID" +
            "=sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChung10ConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChung10ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTiemChungChinh;User" +
            " ID=sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTiemChungChinhConnectionString {
            get {
                return ((string)(this["DoAn_QLTiemChungChinhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=DoAn_QLTiemChung7;Integrated Security=True;Encrypt" +
            "=False")]
        public string DoAn_QLTiemChung7ConnectionString2 {
            get {
                return ((string)(this["DoAn_QLTiemChung7ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=DoAn_QLTiemChung;Integrated Security=True;Encrypt=" +
            "False")]
        public string DoAn_QLTiemChungConnectionString4 {
            get {
                return ((string)(this["DoAn_QLTiemChungConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=DoAn_QLTTTiemChung;Integrated Security=True;Encryp" +
            "t=False")]
        public string DoAn_QLTTTiemChungConnectionString {
            get {
                return ((string)(this["DoAn_QLTTTiemChungConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=DoAn_QLTTTiemChung2;Integrated Security=True;Encry" +
            "pt=False")]
        public string DoAn_QLTTTiemChung2ConnectionString {
            get {
                return ((string)(this["DoAn_QLTTTiemChung2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SNLG86J\\SQLEXPRESS;Initial Catalog=DoAn_QLTTTiemChung;User ID" +
            "=sa;Password=123456;Encrypt=False")]
        public string DoAn_QLTTTiemChungConnectionString1 {
            get {
                return ((string)(this["DoAn_QLTTTiemChungConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=DoAn_QLTTTiemChung3;Integrated Security=True;Encry" +
            "pt=False")]
        public string DoAn_QLTTTiemChung3ConnectionString {
            get {
                return ((string)(this["DoAn_QLTTTiemChung3ConnectionString"]));
            }
        }
    }
}
